version: '3'
services:
  config:
    build: ./services/config
    image: felixbreuer/instapy-config:latest
    restart: unless-stopped
    ports:
      - 4002:80
    volumes:
      - ./services/config:/usr/instapy
    environment:
      - MODE=development
      - MONGO_URL
      - JWT_SECRET
      - CIPHER_SECRET
    depends_on:
      - mongo
  auth:
    build: ./services/auth
    image: felixbreuer/instapy-auth:latest
    command: ['npm', 'run', 'dev']
    restart: unless-stopped
    volumes:
      - ./services/auth:/usr/instapy
    ports:
      - 4001:80
    environment:
      - MONGO_URL
      - JWT_SECRET
    depends_on:
      - mongo
  socket:
    build: ./services/socket
    image: felixbreuer/instapy-socket:latest
    command: ['npm', 'run', 'dev']
    restart: unless-stopped
    ports:
      - 4005:80
    volumes:
      - ./services/socket:/usr/instapy
    environment:
      - JWT_SECRET
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=asdasdasd
    volumes:
      - ./services/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./dev/mongo:/data/db
    ports:
      - 27017:27017
  instapy:
    build: ./services/instapy
    image: felixbreuer/instapy-client:latest
    restart: unless-stopped
    volumes:
      - ./services/instapy:/usr/instapy
    depends_on:
      - mongo
      - auth
      - config
      - socket
